#!/bin/bash
echo Michigan is famous for being the bedrock of America's auto industry, but the Great Lake State is as perfect a state as they come.
...
15 Best Places to Live in Michigan
Ann Arbor. Source: grego1402 / Flickr. ...
Okemos. Source: Donald Schaberg / Wikimedia. ...
East Grand Rapids. ...
Birmingham. ...
Beverly Hills. ...
Novi. ...
Troy. ...
Farmington Hills. 

